services:
  frontend:
    build: ./frontend
    ports:
      - "3100:3100"
    volumes:
      - ./frontend/src:/app/src

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pingme
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src

  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/pingme
      - FLYWAY_USER=user
      - FLYWAY_PASSWORD=password
    volumes:
      - ./data/migrations:/flyway/sql
    command: migrate